# .github/workflows/jupyter-check.yml
name: Check Jupyter Notebooks

on:
  push:
    paths:
      - '**.ipynb'
  pull_request:
    paths:
      - '**.ipynb'

jobs:
  nb-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install nbformat nbconvert

      - name: Validate Notebooks
        run: |
          for nb in $(find . -name "*.ipynb"); do
            echo "Checking $nb"
            python -m nbconvert --execute --to notebook --inplace "$nb"
          done
